projectTitle = "Team Voided Template"
modId = "transition"
githubRepo = "Teamvoided/Transition"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "MincraftEnistein", "TheEnderCore" ]
majorMinecraftVersion = "1.21"
minecraftVersion = "1.21.1"
fabricLoaderVersion = "0.16.2"
fabricApiVersion = "0.102.1+1.21.1"
fabricLangKotlinVersion = "1.12.1+kotlin.2.0.20"
license = "MIT"
modules = [ ]
modDescription = "Mod to fix broken blocks and items"
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ ]
disableKotlin = true

[mappings]
    # You have 7 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    # CUSTOM: Custom mapping jar. Uses mappings version as file location
    type = "MOJANG"
    version = "1.21.1"
